{
 "title": "Humidifier",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Water level",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "humidifier_water_level" }
   ]
  },
  {
   "title": "Current room temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "humidifier_temp" }
   ]
  },
  {
   "title": "Current room humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "humidifier_humidity" }
   ]
  },
  {
   "title": "Water level",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "humidifier_water_level" }
   ]
  },
  {
   "title": "Room temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "humidifier_temp" }
   ]
  },
  {
   "title": "Room humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "humidifier_humidity" }
   ]
  }
 ]
}